# Bryan Forge X Moonraker user overlay

[authorization]
trusted_clients:
    0.0.0.0/0
cors_domains:
    *

[octoprint_compat]
enable_ufp: false
webcam_enabled: false

[announcements]
subscriptions: []