# Bryan Forge X Moonraker user overlay

[authorization]
trusted_clients:
    0.0.0.0/0
cors_domains:
    *

[octoprint_compat]
enable_ufp: false
webcam_enabled: false

[announcements]
subscriptions: []

[update_manager forge-x]
type: git_repo
path: /root/printer_data/config/mod/
origin: https://github.com/SirrrBryyannn37/ff5m-bryan-forge-x.git
primary_branch: bryan-forge-x
managed_services: forge-x